version: '3.7'

services:
  frontend:
      build: ./frontend
      container_name: dash_app
      restart: always
      expose:
        - 8050
      depends_on:
        - nginx

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=flask
    expose:
      - 8080
    depends_on:
      - frontend
      - nginx
    
  jupyter:
    build: ./jupyter
    container_name: jupyter
    restart: always
    environment:
      - APP_NAME=jupyter
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "jupyter"
  
  